export const ADD_USER = "USER/ADD_USER";
export const DELETE_USER_BY_ID = "USER/DELETE_USERS_BY_ID";
export const EDIT_USER_BY_ID = "USER/EDIT_USER_BY_ID";
export const DELETE_ALL_USERS = "USER/DELETE_ALL_USERS";

export const ADD_CAR = "CAR/ADD_CAR";
export const DELETE_CAR_BY_ID = "CAR/DELETE_CAR_BY_ID";
export const EDIT_CAR_BY_ID = "CAR/EDIT_CAR_BY_ID";
export const DELETE_ALL_CARS = "CAR/DELETE_ALL_CARS";